name 'blag'
maintainer 'Ryan Frizzell'
maintainer_email 'no@bugmenot.com'
license 'all_rights'
description 'Installs/Configures blag'
long_description 'Installs/Configures blag'
version '0.1.0'
issues_url 'https://github.com/ryanjfrizzell/chef-blag/issues'
source_url 'https://github.com/ryanjfrizzell/chef-blag.git'

depends 'nginx', '~> 2.7.6'
